# Generated by Django 5.2.3 on 2025-07-01 17:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_type', models.CharField(choices=[('p', 'Passport'), ('d', 'Driving Licence'), ('n', 'National ID')], max_length=1)),
                ('signature', models.CharField(choices=[('u', 'Upload signature'), ('d', 'Draw signature')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_code', models.CharField(db_index=True, default='891263', max_length=6, unique=True)),
                ('account_number', models.CharField(db_index=True, default='74534234', max_length=8, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('expiry_year', models.PositiveBigIntegerField(choices=[(2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043'), (2044, '2044')])),
                ('card_options', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('card_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=1)),
                ('cvc', models.CharField(max_length=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='account.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('mobile', models.CharField(max_length=11)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('', 'Select your gender'), ('M', 'Male'), ('F', 'Femaie'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('maritus_status', models.CharField(choices=[('', 'Select your status'), ('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('SD', 'Separated'), ('I', 'In a relationship'), ('E', 'Engaged'), ('IACP', 'In a civil partnership'), ('IADP', 'In a domestic partnership'), ('IC', "It's complicated"), ('P', 'Prefer not to say')], max_length=4)),
                ('identification_documents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.identificationdocument')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(default='17122367221', unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cards', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('last_transfer', models.DateTimeField(auto_now=True)),
                ('last_amount_received', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_cards', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.card')),
            ],
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['sort_code', 'account_number'], name='account_ban_sort_co_1dfdf6_idx'),
        ),
    ]
