# Generated by Django 5.2.3 on 2025-07-04 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(db_index=True, default='02307591', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sort_code',
            field=models.CharField(db_index=True, default='733152', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identification_documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identification_documents', to='account.identificationdocument'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='05762626848', unique=True),
        ),
    ]
