# Generated by Django 5.2.3 on 2025-07-04 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_bankaccount_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationdocument',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(db_index=True, default='30111409', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sort_code',
            field=models.CharField(db_index=True, default='935018', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='69473085612', unique=True),
        ),
    ]
