# Generated by Django 5.2.3 on 2025-07-04 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_identificationdocument_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identification_documents',
            field=models.CharField(choices=[('p', 'Passport'), ('d', 'Driving Licence'), ('n', 'National ID')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.CharField(choices=[('u', 'Upload signature'), ('d', 'Draw signature')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(db_index=True, default='06747435', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sort_code',
            field=models.CharField(db_index=True, default='332562', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='68089963798', unique=True),
        ),
        migrations.DeleteModel(
            name='IdentificationDocument',
        ),
    ]
