# Generated by Django 5.2.3 on 2025-07-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_profile_profile_id_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(db_index=True, default='99055843', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sort_code',
            field=models.CharField(db_index=True, default='052946', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='22237268189', unique=True),
        ),
    ]
