# Generated by Django 5.2.3 on 2025-07-10 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_bankaccount_profile_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='profile_id',
            new_name='bank_id',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='70152592620', unique=True),
        ),
    ]
