# Generated by Django 5.2.3 on 2025-07-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_rename_profile_id_bankaccount_bank_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='92250096701', unique=True),
        ),
    ]
