# Generated by Django 5.2.3 on 2025-07-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_wallet_last_transfer_wallet_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(db_index=True, default='73796053141', unique=True),
        ),
    ]
