# Generated by Django 5.2.3 on 2025-07-14 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='account.bankaccount'),
        ),
        migrations.AddField(
            model_name='card',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='account.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bank_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bankaccount'),
        ),
    ]
