# Generated by Django 5.2.3 on 2025-07-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_wallet_cards_card_bank_account_card_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=20),
        ),
    ]
