# Generated by Django 5.2.3 on 2025-07-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_card_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='account',
        ),
    ]
