# Generated by Django 5.2.3 on 2025-07-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_card_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
