# Generated by Django 5.2.3 on 2025-07-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_card_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
