# Generated by Django 5.2.3 on 2025-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_options',
            field=models.CharField(choices=[('V', 'Visa'), ('M', 'MasterCard'), ('D', 'Discover')], max_length=3),
        ),
    ]
