# Generated by Django 5.2.3 on 2025-07-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_historicalprofile_historicalwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sort_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='account_number',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='sort_code',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
