# Generated by Django 5.2.3 on 2025-07-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcard',
            name='card_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
    ]
