# Generated by Django 5.2.3 on 2025-06-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_emaillogger_alter_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='code',
            field=models.CharField(db_index=True, default='534126234', max_length=9),
        ),
    ]
