# Generated by Django 5.2.3 on 2025-06-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='code',
            field=models.CharField(db_index=True, default='680057852', max_length=9),
        ),
    ]
