# Generated by Django 5.2.3 on 2025-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_pin_alter_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='code',
            field=models.CharField(db_index=True, default='185165017', max_length=9),
        ),
    ]
