# Generated by Django 5.2.3 on 2025-06-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_surname_alter_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verification',
            name='code',
            field=models.CharField(db_index=True, default='598896252', max_length=9),
        ),
    ]
