# Generated by Django 5.2.3 on 2025-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0052_alter_verification_code_historicaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='code',
            field=models.CharField(db_index=True, default='611831217', max_length=9),
        ),
    ]
